name: Test Project Card Move

on:
  project_card:
    types:
      - moved

jobs:
  test_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: echo "Project card moved!"
      - name: Debugging Event Payload
        run: echo "${{ toJSON(github.event) }}"
