name: Test Project Item Move

on:
  projects_v2_item:
    types: [moved]

jobs:
  test_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: echo "Project item moved!"
      - name: Debugging Event Payload
        run: echo "${{ toJSON(github.event) }}"
