   name: Test Project Card Move

   on:
     project_card:
       types:
         - moved
     push:
       branches:
         - main # Or your default branch

   jobs:
     test_trigger:
       runs-on: ubuntu-latest
       steps:
         - name: Echo Test
           run: echo "Project card moved or push happened!"
         - name: Debugging Event Payload
           run: echo "${{ toJSON(github.event) }}"
