name: C# Code Execution and Verification

on:
  push:
    branches:
      - main # Or your main branch name
    paths:
      - 'Lógica de Programação/Desafio 1/**'
      - '.github/workflows/main.yml' # Trigger on workflow file changes
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: WIP-Capacitacao-Web-APIs-ASP.NET

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Or your desired .NET version

      - name: Restore dependencies
        working-directory: WIP-Capacitacao-Web-APIs-ASP.NET/Lógica de Programação/Desafio 1
        run: dotnet restore

      - name: Build project
        working-directory: WIP-Capacitacao-Web-APIs-ASP.NET/Lógica de Programação/Desafio 1
        run: dotnet build --configuration Release

      - name: Run C# code and verify multi-line integer output
        working-directory: WIP-Capacitacao-Web-APIs-ASP.NET/Lógica de Programação/Desafio 1
        run: |
          # Run C# code, providing input and capturing output
          {
            echo 1
            echo 2
            echo 3
          } | dotnet run -c Release | tee output.txt

          # Read the actual output
          actual_output=$(cat output.txt)

          # Define the expected multi-line integer output
          expected_output=$'123\n331' # Important: \n for newlines

          # Compare the actual and expected outputs (multi-line comparison)
          if [[ "$actual_output" == "$expected_output" ]]; then
            echo "Multi-line integer verification successful!"
          else
            echo "Multi-line integer verification failed!"
            echo "Expected:"
            echo "$expected_output"
            echo "Actual:"
            echo "$actual_output"
            exit 1
          fi

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: WIP-Capacitacao-Web-APIs-ASP.NET/Lógica de Programação/Desafio 1/output.txt

    
