name: Test Java Code (Desafio 1)
 
on:
  push:
    branches: [main] # Or your main branch name
    paths:
      - 'Lógica de Programação/Desafio 1/**' # Path to your folder
      - '.github/workflows/main.yml' # Trigger on workflow file changes

  pull_request:
    branches: [main] # Or your main branch name
    paths:
      - 'Lógica de Programação/Desafio 1/**' # Path to your folder
      - '.github/workflows/main.yml' # Trigger on workflow file changes

jobs:
  run-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java Code
        working-directory: 'Lógica de Programação/Desafio 1/src' # Correct path!
        run: javac Main.java

      - name: Run and Interact with Java Code
        working-directory: 'Lógica de Programação/Desafio 1' # Correct path
        id: run-java
        run: |
          java Main << EOF > output.txt
          1
          2
          3
          EOF
          cat output.txt
          echo "::set-output name=output::$(cat output.txt)"

      - name: Assertions/Tests (grep - less ideal)
        if: always() && steps.run-java.outcome != 'failure'
        working-directory: 'Lógica de Programação/Desafio 1' # Correct path
        run: |
          # Create a file with the expected output (avoids newline issues in the if)
          echo -e "1\n2\n3\n\n3\n3\n1" > expected.txt  # -e interprets escape sequences
        
          if grep -Ff expected.txt output.txt; then  # -f uses a file for patterns
            echo "Test passed (grep -Ff)!"
          else
            echo "Test failed (grep -Ff)!"
            exit 1
          fi

      - name: Upload Output as Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: 'Lógica de Programação/Desafio 1/output.txt' # Correct path
