name: C# Code Execution and Verification

on:
  push:
    branches:
      - main # Or your main branch name
    paths:
      - 'Lógica de Programação/Desafio 1/**'
      - '.github/workflows/main.yml' # Trigger on workflow file changes
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: WIP-Capacitacao-Web-APIs-ASP.NET

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x' # Or your desired .NET version

      - name: Restore dependencies
        working-directory: WIP-Capacitacao-Web-APIs-ASP.NET/Lógica de Programação/Desafio 1
        run: dotnet restore

      - name: Build project
        working-directory: WIP-Capacitacao-Web-APIs-ASP.NET/Lógica de Programação/Desafio 1
        run: dotnet build --configuration Release

      - name: Run C# code and verify output
        working-directory: WIP-Capacitacao-Web-APIs-ASP.NET/Lógica de Programação/Desafio 1
        run: |
          dotnet run -c Release | tee output.txt

          # Example interaction (replace with your actual interaction logic)
          echo "1\n2\n3" | dotnet run -c Release | tee interaction_output.txt

          # Read the actual output
          actual_output=$(cat output.txt)

          # Define the expected output (replace with your actual expected output)
          expected_output="123\n331\nYou entered: This is some input for the C# program" # Example

          # Compare the actual and expected outputs
          if [[ "$actual_output" == "$expected_output" ]]; then
            echo "Output verification successful!"
          else
            echo "Output verification failed!"
            echo "Expected:"
            echo "$expected_output"
            echo "Actual:"
            echo "$actual_output"
            exit 1 # Fail the workflow if the outputs don't match
          fi

          # Optional: Check Interaction output
          interaction_output=$(cat interaction_output.txt)
          expected_interaction_output="Hello from C#!\nThis is line 2.\nYou entered: This is some input for the C# program" # Example

          if [[ "$interaction_output" == "$expected_interaction_output" ]]; then
            echo "Interaction output verification successful!"
          else
            echo "Interaction output verification failed!"
            echo "Expected:"
            echo "$expected_interaction_output"
            echo "Actual:"
            echo "$interaction_output"
            exit 1 # Fail the workflow if the outputs don't match
          fi

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: output-files
          path: WIP-Capacitacao-Web-APIs-ASP.NET/Lógica de Programação/Desafio 1/output.txt
