name: Test Java Code (Desafio 1)

on:
  push:
    branches: [main] # Or your main branch name
    paths:
      - 'Lógica de Programação/Desafio 1/**' # Path to your folder
      - '.github/workflows/main.yml' # Trigger on workflow file changes

  pull_request:
    branches: [main] # Or your main branch name
    paths:
      - 'Lógica de Programação/Desafio 1/**' # Path to your folder
      - '.github/workflows/main.yml' # Trigger on workflow file changes

jobs:
  run-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java Code
        working-directory: 'Lógica de Programação/Desafio 1/src' # Correct path!
        run: javac main.java

      - name: Run and Interact with Java Code
        working-directory: 'Lógica de Programação/Desafio 1' # Correct path
        id: run-java
        run: |
          java main << EOF > output.txt
          1
          2
          3
          EOF
          cat output.txt
          echo "::set-output name=output::$(cat output.txt)"

      - name: Assertions/Tests (JUnit - Recommended)
        working-directory: 'Lógica de Programação/Desafio 1' # Correct path
        run: |
          mvn test # Or gradle test if you're using Gradle

      - name: Assertions/Tests (grep - less ideal)
        if: always() && steps.run-java.outcome != 'failure'
        working-directory: 'Lógica de Programação/Desafio 1' # Correct path
        run: |
          if grep "Expected Output String" output.txt; then  # Replace with expected string
            echo "1\n2\n3\n\n3\n3\n1"
          else
            echo "Test failed (grep)!"
            exit 1

      - name: Upload Output as Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: 'Lógica de Programação/Desafio 1/output.txt' # Correct path
