name: Assign Board Team to Issue
on:
  workflow_dispatch:
    inputs:
      content_node_id:
        description: 'The content node ID'
        required: true
        type: string

jobs:
  test_node_id:
    runs-on: ubuntu-latest
    steps:
      - name: Log Node ID
        run: echo "Node ID: ${{ github.event.inputs.content_node_id }}"
      - name: Fail if Empty
        if: ${{ !github.event.inputs.content_node_id }}
        run: exit 1
