name: Assign User on Project Item Move

on:
  workflow_dispatch:
    inputs:
      content_node_id:
        description: 'The content node ID (Issue ID)'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      other_project_data:
        description: 'The full json payload of the github project event'
        required: true
        type: string

jobs:
  assign_user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Assign MateusKSC
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueId = '${{ github.event.inputs.content_node_id }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const assignee = 'MateusKSC';
            const issueNumber = issueId.split('_').pop(); // Extract issue number
            console.log(`Extracted Issue Number: ${issueNumber}`); // Log it

            try {
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number: issueNumber,
                assignees: [assignee]
              });
              console.log(`Assigned ${assignee} to issue ${issueId}`);
            } catch (error) {
              console.error(`Failed to assign ${assignee} to issue ${issueId}:`, error);
              console.error('Full Error:', JSON.stringify(error)); // Add this line
            }
