name: Generic Dispatch Handler

on:
  workflow_dispatch:
    inputs:
      content_node_id:
        description: 'The content node ID'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      other_project_data:
        description: 'The full json payload of the github project event'
        required: true
        type: string

jobs:
  handle_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Log the event type and payload
        run: |
          echo "Content Node ID: ${{ github.event.inputs.content_node_id }}"
          echo "Project ID: ${{ github.event.inputs.project_id }}"
          echo "Other Project Data:"
          export OTHER_PROJECT_DATA="${{ github.event.inputs.other_project_data }}"
          echo "$OTHER_PROJECT_DATA" | jq '.'
