name: Validar Quiz IoC, DIP e DI (Primeira Alternativa Correta)

on:
  workflow_dispatch:
    inputs:
      content_node_id:
        description: 'The content node ID (Issue ID)'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      other_project_data:
        description: 'The full json payload of the github project event'
        required: true
        type: string
      done_column_id:
        description: 'The ID of the "Done" column'
        required: true
        type: string
  push:
    paths:
      - '.github/workflows/quiz_validation_IoC_DIP_DI.yml'
