name: Mover Issue 6 para Done

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'ID do projeto v2'
        required: true
        type: string

jobs:
  mover_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Mover Issue para Done
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_PAT }} # Uses ORG_PAT
          script: |
            console.log("ORG_PAT Secret (Mover Issue):", "${{ secrets.ORG_PAT }}"); # Log the secret
            const projectId = "${{ github.event.inputs.project_id }}";
            const issueNumber = 6;

            const projectItemsQuery = `
              query {
                node(id: "${projectId}") {
                  ... on ProjectV2 {
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            number
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;

            const projectItemsResult = await github.graphql(projectItemsQuery);
            const projectItems = projectItemsResult.node.items.nodes;
            const item = projectItems.find(i => i.content?.number === issueNumber);

            if (!item) {
              core.setFailed("Issue não encontrada no projeto.");
              return;
            }

            const moveIssueMutation = `
              mutation {
                updateProjectV2ItemFieldValue(input: {
                  projectId: "${projectId}",
                  itemId: "${item.id}",
                  fieldId: "status",
                  value: "Done"
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `;

            const moveResult = await github.graphql(moveIssueMutation);
            console.log(`[DEBUG] Move Issue Result: ${JSON.stringify(moveResult)}`);
