name: Validar Quiz IoC, DIP e DI (Primeira Alternativa Correta)

on:
  workflow_dispatch:
    inputs:
      content_node_id:
        description: 'The content node ID (Issue ID)'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      other_project_data:
        description: 'The full json payload of the github project event'
        required: true
        type: string

permissions: write-all

jobs:
  validar_quiz:
    runs-on: ubuntu-latest
    steps:
      - name: Buscar Issue pelo Nome
        id: buscar_issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueName = "Desafio quiz: IoC, DIP e DI";
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "all",
            });

            const issue = issues.data.find(issue => issue.title === issueName);

            if (!issue) {
              core.setFailed(`Issue com o nome "${issueName}" não encontrado.`);
              return null;
            }

            console.log(`[DEBUG] Issue Number: ${issue.number}`);
            return issue.number;

      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Obter conteúdo da issue
        id: obter_issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = ${{ steps.buscar_issue.outputs.result }};
            if (!issueNumber) return;

            try {
              const issueBody = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
              }).then(result => result.data.body);

              if (!issueBody) {
                console.log(`Issue number ${issueNumber} body not found.`);
                return;
              }

              return issueBody;
            } catch (error) {
              core.setFailed(`Failed to retrieve issue body: ${error.message}`);
              return;
            }

      - name: Validar respostas do quiz
        id: validar_respostas
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = ${{ steps.obter_issue.outputs.result }};
            const issueNumber = ${{ steps.buscar_issue.outputs.result }};
            const projectId = "${{ github.event.inputs.project_id }}";
            if (!issueBody || !issueNumber) return;

            const respostasCorretas = {
              "1": "Uma disciplina.",
              "2": "Sim.",
              "3": "Um padrão de design que permite injetar dependências, proporcionando baixo acoplamento.",
              "4": "IoC estabelece que as abstrações não devem depender de implementações concretas, enquanto DIP define que os módulos de alto nível não devem depender dos módulos de baixo nível."
            };

            const respostasUsuario = {};
            const perguntas = issueBody.split("# ");

            perguntas.slice(1).forEach(pergunta => {
              const numeroPergunta = pergunta.split(" - ")[0];
              const opcoes = pergunta.split("- [");

              opcoes.slice(1).forEach(opcao => {
                if (opcao.startsWith("x")) {
                  respostasUsuario[numeroPergunta] = opcao.split("] ")[1].trim();
                }
              });
            });

            let feedback = "## Resultado do Quiz\n\n";
            let todasCorretas = true;

            for (const numeroPergunta in respostasCorretas) {
              if (respostasUsuario[numeroPergunta] === respostasCorretas[numeroPergunta]) {
                feedback += `✅ Pergunta ${numeroPergunta}: Resposta correta!\n`;
              } else {
                feedback += `❌ Pergunta ${numeroPergunta}: Resposta incorreta. Resposta correta: ${respostasCorretas[numeroPergunta]}\n`;
                todasCorretas = false;
              }
            }

            if (todasCorretas) {
              feedback += "\nParabéns! Você acertou todas as perguntas do quiz.";
            } else {
              feedback += "\nPor favor, revise suas respostas e tente novamente.";
            }

            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: feedback,
              });
            } catch (error) {
              core.setFailed(`Failed to create issue comment: ${error.message}`);
            }

            // Mover card se todas as respostas estiverem corretas
            if (todasCorretas) {
              try {
                const projectColumns = await github.rest.projects.listColumns({
                  project_id: projectId,
                });

                if (projectColumns && projectColumns.data && projectColumns.data.length > 2) {
                  const reviewColumnId = projectColumns.data[1].id; // Review é a segunda coluna
                  const doneColumnId = projectColumns.data[2].id; // Done é a terceira coluna

                  // Busca o card associado ao issue
                  const projectCards = await github.rest.projects.listCards({
                    column_id: reviewColumnId, // Busca cards na coluna Review
                  });

                  const cardToMove = projectCards.data.find(card => card.content_url === issue.html_url);

                  if (cardToMove) {
                    console.log(`[DEBUG] Card to Move: ${JSON.stringify(cardToMove)}`);
                    console.log(`[DEBUG] Card ID: ${cardToMove.id}`);
                    console.log(`[DEBUG] Done Column ID: ${doneColumnId}`);

                    await github.rest.projects.moveCard({
                      card_id: cardToMove.id,
                      position: "bottom",
                      column_id: doneColumnId,
                    }).then(result => {
                        console.log(`[DEBUG] moveCard Result: ${result.status}`);
                    });
                  } else {
                    console.log("Card associado ao issue não encontrado na coluna Review.");
                  }
                } else {
                  console.log("Coluna 'Review' ou 'Done' não encontrada ou projeto tem menos de 3 colunas.");
                }
              } catch (moveError) {
                core.setFailed(`Falha ao mover card: ${moveError.message}`);
              }
            }
