name: Validar Quiz IoC, DIP e DI (Primeira Alternativa Correta)

on:
  workflow_dispatch:
    inputs:
      content_node_id:
        description: 'The content node ID (Issue ID)'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      other_project_data:
        description: 'The full json payload of the github project event'
        required: true
        type: string

permissions: write-all

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add marker to issue 6 body
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            const issueNumber = 6;
            await github.rest.issues.update({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "issue:done"
            });
            console.log(`Added marker to issue #${issueNumber} body`);

      - name: Move issue 6 to Done Column
        uses: fojia/action-move-issues-to-column@master
        with:
          project: ${{ github.event.inputs.project_id }}
          column: 'Done'
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          type: 'repo'
          github_token: ${{ secrets.ORG_PAT }}
          marker: 'issue:done'
