name: Validar Quiz Riscos da Ausência de Versionamento
on:
  push:
    paths:
      - '.github/workflows/quiz_validation.yml'

permissions:
  write-all # Still recommend narrowing this down

jobs:
  validar_quiz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Obter conteúdo da issue
        id: obter_issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitulo = "Desafio quiz: Riscos da Ausência de Versionamento";
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });

            const issue = issues.data.find(i => i.title === issueTitulo);

            if (!issue) {
              console.log(`Issue "${issueTitulo}" não encontrada.`);
              return null; // Return null if no issue found
            }

            return issue.body;

      - name: Validar respostas do quiz
        id: validar_respostas
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = ${{ steps.obter_issue.outputs.result }};
            if (!issueBody) return;

            const respostasCorretas = {
              "1": "Fica difícil encontrar e corrigir os erros, atrasando o trabalho.",
              "2": "A origem dos erros é difícil de encontrar, atrasando o trabalho.",
              "3": "Não, sem um sistema de versionamento, a recuperação de versões anteriores do programa é altamente improvável e não confiável.",
              "4": "Dificulta a colaboração, pois as alterações de múltiplos desenvolvedores podem se sobrepor e causar problemas.",
              "5": "Fica mais difícil e demorado criar novas versões do programa."
            };

            const respostasUsuario = {};
            const perguntas = issueBody.split("# ");

            perguntas.slice(1).forEach(pergunta => {
              const numeroPergunta = pergunta.split(" - ")[0];
              const opcoes = pergunta.split("- [");

              opcoes.slice(1).forEach(opcao => {
                if (opcao.startsWith("x")) {
                  respostasUsuario[numeroPergunta] = opcao.split("] ")[1].trim();
                }
              });
            });

            let feedback = "## Resultado do Quiz (triggered on push - potential issue target)\n\n";
            let todasCorretas = true;

            const issuesList = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
            });

            const targetIssue = issuesList.data.find(i => i.title === "Desafio quiz: Riscos da Ausência de Versionamento");

            if (targetIssue) {
              for (const numeroPergunta in respostasCorretas) {
                if (respostasUsuario[numeroPergunta] === respostasCorretas[numeroPergunta]) {
                  feedback += `✅ Pergunta ${numeroPergunta}: Resposta correta!\n`;
                } else {
                  feedback += `❌ Pergunta ${numeroPergunta}: Resposta incorreta. Resposta correta: ${respostasCorretas[numeroPergunta]}\n`;
                  todasCorretas = false;
                }
              }

              if (todasCorretas) {
                feedback += "\nParabéns! Você acertou todas as perguntas do quiz.";
              } else {
                feedback += "\nPor favor, revise suas respostas e tente novamente.";
              }

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: targetIssue.number,
                body: feedback,
              });
            } else {
              console.log(`Não foi possível encontrar a issue "${issueTitulo}" para comentar.`);
            }

            return feedback; # Optionally return feedback
