jobs:
  mover_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Mover Issue para Done
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            console.log("ORG_PAT Secret (Mover Issue):", "${{ secrets.ORG_PAT }}");
            console.log("Project Id:", "${{ github.event.inputs.project_id }}");

            const projectId = "${{ github.event.inputs.project_id }}";
            const issueNumber = context.issue.number;

            console.log(`Issue Number: ${issueNumber}`);

            const projectItemsQuery = `
              query {
                node(id: "${projectId}") {
                  ... on ProjectV2 {
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            number
                          }
                        }
                      }
                    }
                    fields(first: 100) {
                      nodes {
                        id
                        name
                        ... on ProjectV2ItemFieldSingleSelect {
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;

            try {
              const projectItemsResult = await github.graphql(projectItemsQuery);
              const projectItems = projectItemsResult.node.items.nodes;
              const item = projectItems.find(i => i.content?.number === issueNumber);

              if (!item) {
                core.setFailed(`Issue ${issueNumber} não encontrada no projeto.`);
                return;
              }

              const doneColumn = projectItemsResult.node.fields.nodes.find(field => field.__typename === "ProjectV2ItemFieldSingleSelect" && field.name === "Done");
              const reviewColumn = projectItemsResult.node.fields.nodes.find(field => field.__typename === "ProjectV2ItemFieldSingleSelect" && field.name === "Review");

              if (!doneColumn || !reviewColumn) {
                core.setFailed("Colunas 'Done' ou 'Review' não encontradas no projeto.");
                return;
              }

              const doneOption = doneColumn.options.find(option => option.name === "Done");
              const reviewOption = reviewColumn.options.find(option => option.name === "Review");

              if (!doneOption || !reviewOption) {
                core.setFailed("Opções 'Done' ou 'Review' não encontradas nas colunas.");
                return;
              }

              const moveIssueMutation = `
                mutation {
                  updateProjectV2ItemPosition(input: {
                    projectId: "${projectId}",
                    itemId: "${item.id}",
                    afterId: null,
                    fieldValueId: "${doneOption.id}"
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;

              const moveResult = await github.graphql(moveIssueMutation);
              console.log(`[DEBUG] Move Issue Result: ${JSON.stringify(moveResult)}`);
            } catch (error) {
              core.setFailed(`Error moving issue: ${error.message}`);
              console.error(`Error: ${error}`);
            }
