name: Test Node ID

on:
  workflow_dispatch:
    inputs:
      content_node_id:
        description: 'The content node ID (Issue ID)'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      other_project_data:
        description: 'The full json payload of the github project event'
        required: true
        type: string
jobs:
  test_node_id:
    runs-on: ubuntu-latest
    steps:
      - name: Log Node ID
        run: |
          echo "Node ID: ${{ github.event.inputs.content_node_id }}"
      - name: Fail if Empty
        if: ${{ github.event.inputs.content_node_id == '' }}
        run: exit 1
