name: Validar Quiz IoC, DIP e DI (Primeira Alternativa Correta)

on:
  workflow_dispatch:
    inputs:
      content_node_id:
        description: 'The content node ID (Issue ID)'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      other_project_data:
        description: 'The full json payload of the github project event'
        required: true
        type: string

permissions: write-all


jobs:
  mover_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Mover Issue para Done
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            console.log("ORG_PAT Secret (Mover Issue):", "${{ secrets.ORG_PAT }}");
            const projectId = "${{ github.event.inputs.project_id }}";
            const issueNumber = parseInt("${{ github.event.inputs.issue_number }}"); # Corrected line.

            console.log(`Moving issue number: ${issueNumber}`);

            const projectItemsQuery = `
              query {
                node(id: "${projectId}") {
                  ... on ProjectV2 {
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            number
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;

            try {
              const projectItemsResult = await github.graphql(projectItemsQuery);
              const projectItems = projectItemsResult.node.items.nodes;
              const item = projectItems.find(i => i.content?.number === issueNumber);

              if (!item) {
                core.setFailed(`Issue ${issueNumber} não encontrada no projeto.`);
                return;
              }

              const moveIssueMutation = `
                mutation {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: "${projectId}",
                    itemId: "${item.id}",
                    fieldId: "status",
                    value: "Done"
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;

              const moveResult = await github.graphql(moveIssueMutation);
              console.log(`[DEBUG] Move Issue Result: ${JSON.stringify(moveResult)}`);
            } catch (error) {
              core.setFailed(`Error moving issue: ${error.message}`);
              console.error(`Error: ${error}`);
            }
