name: Validar Quiz IoC, DIP e DI (Primeira Alternativa Correta)

on:
  workflow_dispatch:
    inputs:
      content_node_id:
        description: 'The content node ID (Issue ID)'
        required: true
        type: string
      project_id:
        description: 'The project ID'
        required: true
        type: string
      other_project_data:
        description: 'The full json payload of the github project event'
        required: true
        type: string
  push:
    paths:
      - '.github/workflows/quiz_validation_IoC_DIP_DI.yml'

permissions: write-all

jobs:
  test_query:
    runs-on: ubuntu-latest
    steps:
      - name: Run GraphQL Query
        uses: actions/github-script@v6
        with:
          script: |
            const nodeId = "${{ github.event.inputs.node_id }}";
            console.log(`[DEBUG] Node ID: ${nodeId}`);
            const query = `
              query {
                node(id: "${nodeId}") {
                  ... on Issue {
                    number
                  }
                }
              }
            `;
            try {
              const response = await github.graphql(query);
              console.log(JSON.stringify(response, null, 2));
            } catch (error) {
              console.error("GraphQL Error:", error);
              core.setFailed(error.message);
            }
